import gspread
from google.oauth2.service_account import Credentials
import json
import os
from datetime import datetime

def get_gspread_client():
    scopes = ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive']
    
    # Priority 1: GitHub Secrets / Environment
    creds_json = os.environ.get('GOOGLE_CREDS') or os.environ.get('GSPREAD_SERVICE_ACCOUNT')
    
    # Priority 2: config.json
    config_path = os.path.join(os.path.dirname(__file__), 'config.json')
    config = {}
    if os.path.exists(config_path):
        with open(config_path, 'r') as f:
            config = json.load(f)
            if not creds_json:
                creds_json = config.get('google_creds')

    if creds_json:
        creds_dict = json.loads(creds_json) if isinstance(creds_json, str) else creds_json
        creds = Credentials.from_service_account_info(creds_dict, scopes=scopes)
    else:
        # Fallback to local file
        creds_path = os.path.join(os.path.dirname(__file__), 'service_account.json')
        if os.path.exists(creds_path):
            creds = Credentials.from_service_account_file(creds_path, scopes=scopes)
        else:
            raise FileNotFoundError("Google credentials not found in environment or service_account.json")
            
    return gspread.authorize(creds)

def get_target_sheet():
    config_path = os.path.join(os.path.dirname(__file__), 'config.json')
    if os.path.exists(config_path):
        with open(config_path, 'r') as f:
            return json.load(f).get('gsheet_target', 'Keuangan')
    return os.environ.get('GSHEET_TARGET', 'Keuangan')

def sync_transactions(sheet_id, local_json_path):
    client = get_gspread_client()
    sh = client.open_by_key(sheet_id)
    ws = sh.worksheet('Money_tracker')
    
    # Load local transactions
    if not os.path.exists(local_json_path):
        print(f"Local transaction file not found: {local_json_path}")
        return
        
    with open(local_json_path, 'r') as f:
        local_data = json.load(f)
        # Ensure it's a list (web app might store as object with 'transactions' key)
        local_txs = local_data.get('transactions', local_data) if isinstance(local_data, dict) else local_data

    # Read GSheet data to avoid duplicates
    # We use a composite key for uniqueness (Date + Account + Category + Description + Amount)
    gsheet_rows = ws.get_all_values()
    gsheet_keys = set()
    if len(gsheet_rows) > 1:
        headers = [h.lower().strip() for h in gsheet_rows[0]]
        # Map headers to indices
        idx_map = {
            'date': headers.index('date') if 'date' in headers else 0,
            'account': headers.index('account') if 'account' in headers else 1,
            'category': headers.index('category') if 'category' in headers else 2,
            'desc': headers.index('description') if 'description' in headers else 3,
            'amount': headers.index('idr') if 'idr' in headers else 5,
        }
        
        for row in gsheet_rows[1:]:
            key = (
                row[idx_map['date']], 
                row[idx_map['account']], 
                row[idx_map['category']], 
                row[idx_map['desc']], 
                row[idx_map['amount']].replace('Rp', '').replace('.', '').replace(',', '').strip()
            )
            gsheet_keys.add(key)

    # Identifty missing transactions
    new_rows = []
    for tx in local_txs:
        # Normalize local data
        date_str = tx.get('date', '').split('T')[0]
        amount_str = str(int(tx.get('amount', 0)))
        
        key = (
            date_str,
            tx.get('paymentMethod', ''),
            tx.get('category', ''),
            tx.get('description', ''),
            amount_str
        )
        
        if key not in gsheet_keys:
            # Prepare row for GSheet: Date, Account, Category, Description, Item, IDR, Type
            row = [
                date_str,
                tx.get('paymentMethod', ''),
                tx.get('category', ''),
                tx.get('description', ''),
                '', # Item
                tx.get('amount', 0),
                'Income' if tx.get('type') == 'income' else 'Outcome'
            ]
            new_rows.append(row)

    if new_rows:
        print(f"Pushing {len(new_rows)} new transactions to GSheet...")
        # Use append_rows with USER_ENTERED to preserve formatting
        ws.append_rows(new_rows, value_input_option='USER_ENTERED')
        print("Sync complete.")
    else:
        print("No new transactions to sync.")

if __name__ == "__main__":
    SHEET_ID = get_target_sheet()
    # Use the backup file generated by the web app's Drive sync/download
    LOCAL_DATA = 'data/money-tracker-backup.json'
    if not os.path.exists(LOCAL_DATA):
        # Fallback to a general transactions.json if available
        LOCAL_DATA = 'data/transactions.json'
    sync_transactions(SHEET_ID, LOCAL_DATA)
